name: thermofun-jupyter
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - pip
  - thermofun
  - thermohubclient
  - jupyter
  - pip:
    - pandas
    - matplotlib
    - IPython
    - voila
    - py4j
    - beakerx
