name: thermofun-jupyter
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - pip
  - thermofun>=0.2.2
  - pip:
    - pandas
    - matplotlib
    - IPython
    - voila
    - py4j
    - beakerx
